import { ApiProperty } from '@nestjs/swagger';
import { IsString } from 'class-validator';
import { Expose } from 'class-transformer';
import {
  IMacroCycleModel,
  TBaseModelAutogeneratedProps,
  TMacroCycleModelArrayModelProps,
} from '@powerbuilding-trainer/shared/core';

type TCreateMacroCycleDTO = Omit<
  IMacroCycleModel,
  TBaseModelAutogeneratedProps | TMacroCycleModelArrayModelProps
>;

export class CreateMacroCycleDTO implements TCreateMacroCycleDTO {
  @ApiProperty()
  @Expose()
  @IsString()
  public name: string;

  constructor(dto: CreateMacroCycleDTO) {
    Object.assign(this, dto);
  }
}
